eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: email-client

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/helpdesk'
    username: helpdesk_app
    password: helpdesk
    hikari:
      schema: helpdesk
      connectionTimeout: 30000
      initialization-fail-timeout: 60000
      maximumPoolSize: 10
      auto-commit: false

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        connection:
          provider_disables_autocommit: true
        cache:
          use_second_level_cache: false
        jdbc:
          batch_size: 30
          lob:
            non_contextual_creation: true

  liquibase:
    contexts: prod
    enabled: true
    default-schema: public
    user: helpdesk
    password: helpdesk

  mail:
    host: smtp.yandex.com
    username: helpdesk.gdf
    password: Tha0xi7k
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    imap:
      host: imap.yandex.com
      security: SSL
      port: 993

  kafka:
    enable: true
    bootstrap-servers: "localhost:9092"

    topic:
      emailIn: "email.in.v1.pub"
      emailOut: "email.out.v1.pub"


    consumer:
      group-id: "email-client-0001"
      key-deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      value-deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      enable-auto-commit: true
      auto-offset-reset: true
      properties:
        max-poll-ms-intervall: 1000

    producer:
      key-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"



    kafka:
      #build: .
      image: wurstmeister/kafka
      ports:
        - 9092:9092
      environment:
        KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
        KAFKA_CREATE_TOPICS: "email.in.v1.pub:2:3,email.out.v1.pub:2:3"
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
