debug: true
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: email-client

spring:
  mail:
    host: smtp.yandex.com
    username: helpdesk.gdf
    password: Tha0xi7k
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
    imap:
      host: imap.yandex.com
      port: 993
      userFlag: client18

  kafka:
    enable: true
    bootstrap-servers: "localhost:9092"

    topic:
      emailIn: "email.in.v1.pub"
      emailOut: "helpdesk.gdf_yandex.com.v1.pub"

    properties:
      schema.registry.url: "http://localhost:8081"
      specific.avro.reader: true

    consumer:
      group-id: "email-client-0011"
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      enable-auto-commit: true
      auto-offset-reset: earliest
      properties:
        max-poll-ms-intervall: 1000

    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

logging:
  file:
    clean-history-on-start: true
