debug: true
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: email-client

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/helpdesk'
    username: helpdesk_app
    password: helpdesk
    hikari:
      schema: helpdesk
      connectionTimeout: 30000
      initialization-fail-timeout: 60000
      maximumPoolSize: 10
      auto-commit: false

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        connection:
          provider_disables_autocommit: true
        cache:
          use_second_level_cache: false
        jdbc:
          batch_size: 30
          lob:
            non_contextual_creation: true

  liquibase:
    contexts: prod
    enabled: true
    default-schema: public
    user: helpdesk
    password: helpdesk

  mail:
    host: smtp.yandex.com
    username: helpdesk.gdf
    password: Tha0xi7k
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
    imap:
      host: imap.yandex.com
      port: 993
      userFlag: client18

  kafka:
    enable: true
    bootstrap-servers: "localhost:9092"

    topic:
      emailIn: "email.in.v1.pub"
      emailOut: "email.out.v1.pub"

    properties:
      schema.registry.url: "http://localhost:8081"
      specific.avro.reader: true

    consumer:
      group-id: "email-client-0011"
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      enable-auto-commit: true
      auto-offset-reset: earliest
      properties:
        max-poll-ms-intervall: 1000

    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

logging:
  file:
    clean-history-on-start: true

  level:
    org.springfamework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    com.zaxxer.hikari: DEBUG

