debug: true
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: helpdesk-backend


keycloak:
  auth-server-url: http://172.17.0.1:8082/auth/
  resource: helpdesk-backend
  realm: helpdesk
  .public-client: false
  credentials:
    secret: a19c684e-3cd7-461d-8da9-78fd53136710

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/helpdesk'
    username: helpdesk_app
    password: helpdesk
    hikari:
      schema: helpdesk
      connectionTimeout: 30000
      initialization-fail-timeout: 60000
      maximumPoolSize: 10
      auto-commit: false

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        connection:
          provider_disables_autocommit: true
        cache:
          use_second_level_cache: false
        jdbc:
          batch_size: 30
          lob:
            non_contextual_creation: true

  liquibase:
    contexts: prod
    enabled: true
    default-schema: public
    user: helpdesk
    password: helpdesk

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}realms/helpdesk

  kafka:
    enable: true
    bootstrap-servers: "localhost:9092"

    topic:
      emailIn: "email.in.v1.pub"
      emailOutSuffix: ".v1.pub"

    properties:
      schema.registry.url: "http://localhost:8081"
      specific.avro.reader: true

    consumer:
      group-id: "helpdesk-backend-0005"
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      enable-auto-commit: true
      auto-offset-reset: earliest
      properties:
        max-poll-ms-intervall: 1000

    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

logging:
  file:
    clean-history-on-start: true

  level:
    org.springfamework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    com.zaxxer.hikari: DEBUG

