version: '3.7'
services:
  helpdesk-backend:
    ports:
      - 8080:8080
    image: helpdesk-backend
    environment:
      EUREKA_CLIENT_ENABLED: "true"
      SPRING_MAIL_HOST: smtp.yandex.com
      SPRING_MAIL_IMAP_HOST: imap.yandex.com
      SPRING_MAIL_USERNAME: helpdesk.gdf
      SPRING_MAIL_PASSWORD: Tha0xi7k
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/helpdesk
      KEYCLOAK_AUTH_SERVER_URL: http://172.17.0.1:8082/auth/
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://172.17.0.1:8082/auth/realms/helpdesk
      SPRING_KAFKA_CONSUMER_GROUPID: "helpdesk-backend-0005"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://172.17.0.1:8761/eureka/
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:9092
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: schema-registry:8081
    depends_on:
      - eureka
      - db
      - prometheus


  email-client-generic:
    image: email-client
    environment:
      SPRING_KAFKA_TOPIC_EMAILOUT: "helpdesk.gdf_yandex.com.v1.pub"
      SPRING_MAIL_HOST: smtp.yandex.com
      SPRING_MAIL_IMAP_HOST: imap.yandex.com
      SPRING_MAIL_USERNAME: helpdesk.gdf
      SPRING_MAIL_PASSWORD: Tha0xi7k
      EUREKA_CLIENT_ENABLED: "true"
      SPRING_MAIL_IMAP_USERFLAG: "client40"
      SPRING_KAFKA_CONSUMER_GROUPID: "email-client-0012"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://172.17.0.1:8761/eureka/
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:9092
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: schema-registry:8081
    depends_on:
      - eureka
      - zookeeper
      - kafka

  email-client-travel:
    image: email-client
    environment:
      SPRING_KAFKA_TOPIC_EMAILOUT: "helpdesk.gdf.travel_yandex.com.v1.pub"
      SPRING_MAIL_HOST: smtp.yandex.com
      SPRING_MAIL_IMAP_HOST: imap.yandex.com
      SPRING_MAIL_USERNAME: helpdesk.gdf.travel
      SPRING_MAIL_PASSWORD: Xo8nua4o
      EUREKA_CLIENT_ENABLED: "true"
      SPRING_MAIL_IMAP_USERFLAG: "client40"
      SPRING_KAFKA_CONSUMER_GROUPID: "email-client-0012"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://172.17.0.1:8761/eureka/
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:9092
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: schema-registry:8081
    depends_on:
      - eureka
      - zookeeper
      - kafka

  email-client-theater:
    image: email-client
    environment:
      SPRING_KAFKA_TOPIC_EMAILOUT: "h.gdf.theater_gmx.com.v1.pub"
      SPRING_MAIL_HOST: mail.gmx.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SOCKETFACTORY_PORT: 587
      SPRING_MAIL_IMAP_HOST: imap.gmx.com
      SPRING_MAIL_USERNAME: h.gdf.theater@gmx.com
      SPRING_MAIL_PASSWORD: Thu9esejThu9esej
      EUREKA_CLIENT_ENABLED: "true"
      SPRING_MAIL_IMAP_USERFLAG: "client40"
      SPRING_KAFKA_CONSUMER_GROUPID: "email-client-0012"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://172.17.0.1:8761/eureka/
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:9092
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: schema-registry:8081
    depends_on:
      - eureka
      - zookeeper
      - kafka

  eureka:
    image: springcloud/eureka
    ports:
      - 8761:8761

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    ports:
      - 15432:8080
    environment:
      ADMINER_DESIGN: hever

  keycloak:
    image: quay.io/keycloak/keycloak:11.0.2
    volumes:
      - ./keycloak:/opt/jboss/keycloak/imports
    ports:
      - 8082:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json


  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/mydashboard.json:/var/lib/grafana/dashboards/mydashboard.json
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    environment:
      GF_PATH_PROVISIONING: "/etc/grafana/provisioning"


  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_CREATE_TOPICS: "email.in.v1.pub:2:3,helpdesk.gdf_yandex.com.v1.pub:2:3,helpdesk.gdf.travel_yandex.com.v1.pub:2:3,h.gdf.theater_gmx.com.v1.pub:2:3"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  clusterManager:
    image: vimagick/cmak
    ports:
      - 9093:9000
    environment:
      ZK_HOSTS: zookeeper:2181
    depends_on:
      - kafka
      - zookeeper

  schema-registry:
    image: confluentinc/cp-schema-registry
    ports:
      - 8081:8081
    depends_on:
      - zookeeper
      - kafka
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
