CREATE USER sonarqube WITH PASSWORD 'sonarqube';
CREATE DATABASE sonarqube;
GRANT ALL PRIVILEGES ON DATABASE sonarqube TO sonarqube;

CREATE USER HELPDESK WITH PASSWORD 'helpdesk';
CREATE DATABASE helpdesk;
GRANT ALL PRIVILEGES ON DATABASE helpdesk TO HELPDESK;

CREATE ROLE helpdesk_app WITH LOGIN PASSWORD 'helpdesk';