CREATE USER keycloak WITH PASSWORD 'keycloak';
CREATE DATABASE keycloak;
GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;

CREATE USER HELPDESK WITH PASSWORD 'helpdesk';
CREATE DATABASE helpdesk;
GRANT ALL PRIVILEGES ON DATABASE helpdesk TO HELPDESK;

CREATE ROLE helpdesk_app WITH LOGIN PASSWORD 'helpdesk';